import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { createNeonTestPool } from "../helpers/neon-pool";
import { authFixtures } from "./auth-fixtures";
import { login, loginAsStudent } from "./auth-helpers";

test.describe.configure({mode:"serial"});
const themeName="Atividades FM-013 E2E";let activityId="";let enrollmentId="";let createdEnrollment=false;const questionIds:string[]=[];

test.beforeAll(async()=>{const {pool}=createNeonTestPool();try{const rows=await pool.query(`SELECT u1."id" AS "teacherId",u2."id" AS "adminId",u3."id" AS "studentId",s."id" AS "schoolId",c."id" AS "classId" FROM "User" u1,"User" u2,"User" u3,"School" s,"ClassGroup" c WHERE u1."normalizedEmail"=$1 AND u2."normalizedEmail"=$2 AND u3."studentCode"=$3 AND s."externalCode"=$4 AND c."schoolId"=s."id" AND c."name"=$5`,[authFixtures.schools.teacherOne.email,authFixtures.recovery.adminEmail,authFixtures.student.identifier,authFixtures.schools.schoolA.code,authFixtures.people.classA]);const row=rows.rows[0];const themeId=randomUUID();await pool.query(`INSERT INTO "Theme" ("id","name","normalizedName","status","revision","createdAt","updatedAt") VALUES ($1,$2,$3,'ACTIVE',1,NOW(),NOW())`,[themeId,themeName,themeName.toLocaleLowerCase("pt-BR")]);for(let difficulty=1;difficulty<=6;difficulty++){const network=difficulty<=3;const questionId=randomUUID();questionIds.push(questionId);await pool.query(`INSERT INTO "Question" ("id","origin","ownerId","createdById","status","revision","latestVersionNumber","createdAt","updatedAt") VALUES ($1,$2::"QuestionOrigin",$3,$4,'ACTIVE',1,1,NOW(),NOW())`,[questionId,network?"SEMED":"PRIVATE",network?null:row.teacherId,network?row.adminId:row.teacherId]);await pool.query(`INSERT INTO "QuestionVersion" ("id","questionId","versionNumber","grade","difficulty","themeId","statement","answerType","numericExpected","contentHash","createdById","createdAt") VALUES ($1,$2,1,4,$3,$4,$5,'NUMERIC',$6,$7,$8,NOW())`,[randomUUID(),questionId,difficulty,themeId,`Questão E2E da dificuldade ${difficulty}.`,String(difficulty),`${difficulty}`.padEnd(64,"0"),network?row.adminId:row.teacherId]);}const existing=await pool.query(`SELECT "id" FROM "Enrollment" WHERE "studentId"=$1 AND "classId"=$2 AND "status"='ACTIVE'`,[row.studentId,row.classId]);enrollmentId=existing.rows[0]?.id??randomUUID();if(!existing.rows[0]){await pool.query(`INSERT INTO "Enrollment" ("id","studentId","schoolId","classId","status","startsAt","revision","createdAt","updatedAt") VALUES ($1,$2,$3,$4,'ACTIVE',NOW(),1,NOW(),NOW())`,[enrollmentId,row.studentId,row.schoolId,row.classId]);createdEnrollment=true;}}finally{await pool.end();}});

test.afterAll(async()=>{const {pool}=createNeonTestPool();try{if(activityId){await pool.query(`DELETE FROM "GameAction" WHERE "gameId" IN (SELECT g."id" FROM "GameSession" g JOIN "ActivityParticipation" p ON p."id"=g."participationId" WHERE p."activityId"=$1)`,[activityId]);await pool.query(`DELETE FROM "GameChallenge" WHERE "gameId" IN (SELECT g."id" FROM "GameSession" g JOIN "ActivityParticipation" p ON p."id"=g."participationId" WHERE p."activityId"=$1)`,[activityId]);await pool.query(`DELETE FROM "GameSession" WHERE "participationId" IN (SELECT "id" FROM "ActivityParticipation" WHERE "activityId"=$1)`,[activityId]);await pool.query(`DELETE FROM "ActivityAnswerReceipt" WHERE "participationId" IN (SELECT "id" FROM "ActivityParticipation" WHERE "activityId"=$1)`,[activityId]);await pool.query(`DELETE FROM "ActivityParticipation" WHERE "activityId"=$1`,[activityId]);await pool.query(`DELETE FROM "ActivityQuestionVersion" WHERE "activityId"=$1`,[activityId]);await pool.query(`DELETE FROM "AuditEvent" WHERE "targetType"='Activity' AND "targetId"=$1`,[activityId]);await pool.query(`DELETE FROM "Activity" WHERE "id"=$1`,[activityId]);}if(createdEnrollment&&enrollmentId)await pool.query(`DELETE FROM "Enrollment" WHERE "id"=$1`,[enrollmentId]);await pool.query(`DELETE FROM "QuestionVersion" WHERE "questionId"=ANY($1::uuid[])`,[questionIds]);await pool.query(`DELETE FROM "Question" WHERE "id"=ANY($1::uuid[])`,[questionIds]);await pool.query(`DELETE FROM "Theme" WHERE "normalizedName"=$1`,[themeName.toLocaleLowerCase("pt-BR")]);}finally{await pool.end();}});

async function enterTeacher(page: import("@playwright/test").Page){await login(page,authFixtures.schools.teacherOne.email);await expect(page).not.toHaveURL(/\/login$/);if(/selecionar-escola/.test(page.url()))await page.getByRole("listitem").filter({hasText:authFixtures.schools.schoolA.name}).getByRole("button",{name:"Acessar escola"}).click();await expect(page).toHaveURL(/\/professor$/);}

test("professor cobre 1–6, abre; aluno vê progresso e recebe encerramento preservado",async({browser})=>{test.setTimeout(120_000);const teacherContext=await browser.newContext({viewport:{width:390,height:844}});const teacherPage=await teacherContext.newPage();await enterTeacher(teacherPage);await teacherPage.goto("/atividades/nova");await teacherPage.getByRole("heading",{name:"Nova atividade"}).waitFor();const form=teacherPage.getByRole("heading",{name:"Cobertura das dificuldades"}).locator("xpath=ancestor::form");await form.getByLabel("Título").fill("Meta mista E2E");await form.getByLabel("Meta de respostas aceitas").fill("2");const checks=form.getByRole("checkbox");await expect(checks).toHaveCount(6);for(let index=0;index<5;index++)await checks.nth(index).check();await expect(form.getByRole("status")).toContainText("Faltam: 6");await form.getByRole("button",{name:"Criar rascunho"}).click();const createdLink=form.getByRole("link",{name:"Abrir rascunho"});await expect(createdLink).toBeVisible();activityId=(await createdLink.getAttribute("href"))!.split("/").pop()!;await createdLink.click();await expect(teacherPage.getByRole("button",{name:"Abrir atividade"})).toBeDisabled();const edit=teacherPage.getByRole("heading",{name:"Editar rascunho"}).locator("xpath=following::form[1]");await edit.getByRole("checkbox").last().check();await expect(edit.getByRole("status")).toHaveText("Cobertura completa");await edit.getByRole("button",{name:"Salvar rascunho"}).click();await expect(edit.getByText("Rascunho atualizado.")).toBeVisible();await teacherPage.reload();await teacherPage.getByRole("button",{name:"Abrir atividade"}).click();await expect(teacherPage.getByRole("button",{name:"Encerrar atividade"})).toBeVisible();

const studentContext=await browser.newContext({viewport:{width:390,height:844}});const studentPage=await studentContext.newPage();await loginAsStudent(studentPage);await expect(studentPage).toHaveURL(/\/aluno$/);await expect(studentPage.getByText("Meta mista E2E")).toBeVisible();await studentPage.getByRole("link",{name:"Ver progresso"}).click();await expect(studentPage.getByText("Ainda não iniciada")).toBeVisible();await expect(studentPage.getByText("0/2")).toBeVisible();

await studentPage.getByRole("button",{name:"Iniciar partida"}).click();await expect(studentPage.getByRole("heading",{name:"Partida de Ludo"})).toBeVisible();const gameId=await studentPage.locator('input[name="gameId"]').inputValue();const hostileStatus=await teacherPage.evaluate(async(id)=>{const response=await fetch(`/api/jogos/${id}/rolar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientActionId:crypto.randomUUID(),expectedRevision:1,dice:6,correct:true})});return response.status;},gameId);expect(hostileStatus).toBe(403);const tampered=await studentPage.evaluate(async(id)=>{const response=await fetch(`/api/jogos/${id}/rolar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientActionId:crypto.randomUUID(),expectedRevision:0,dice:6,questionVersionId:crypto.randomUUID(),correct:true})});return {status:response.status,body:await response.json()};},gameId);expect(tampered).toMatchObject({status:422,body:{error:"VALIDATION"}});for(let attempt=0;attempt<40&&await studentPage.getByRole("heading",{name:"Desafio"}).count()===0;attempt++){await studentPage.getByRole("button",{name:"Lançar dado"}).click();await expect(studentPage.getByRole("button",{name:"Aguarde..."})).toHaveCount(0,{timeout:15_000});}await expect(studentPage.getByRole("heading",{name:"Desafio"})).toBeVisible();

await teacherPage.getByRole("button",{name:"Encerrar atividade"}).click();await expect(teacherPage.getByRole("button",{name:"Aguarde..."})).toHaveCount(0,{timeout:15_000});await expect(teacherPage.getByRole("button",{name:"Encerrar atividade"})).toHaveCount(0);const {pool}=createNeonTestPool();try{const stored=await pool.query(`SELECT "status" FROM "Activity" WHERE "id"=$1`,[activityId]);expect(stored.rows[0]?.status).toBe("CLOSED");}finally{await pool.end();}await studentPage.goto(`/aluno/atividades/${activityId}?apos-fechamento=1`);await expect(studentPage.getByText("Esta atividade foi encerrada pelo professor. Seu progresso continua salvo.")).toBeVisible();expect(await studentPage.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await teacherContext.close();await studentContext.close();});
