export const authFixtures = {
  password: "FM004-Teste!2026",
  adult: {
    identifier: "fm004.adulto@example.invalid",
    name: "Adulto FM-004",
  },
  student: {
    identifier: "FM004-ALUNO",
    name: "Aluno FM-004",
  },
  blocked: {
    identifier: "fm004.bloqueado@example.invalid",
    name: "Bloqueado FM-004",
  },
  invalidIdentifier: "inexistente@example.invalid",
  rateIdentifier: "limite@example.invalid",
  recovery: {
    adminEmail: "fm005.admin@example.invalid",
    requestEmail: "fm005.solicitacao@example.invalid",
    resetEmail: "fm005.recuperacao@example.invalid",
    resetToken: "fm005-e2e-token-de-uso-unico-2026-00000001",
    newPassword: "Senha-Nova-E2E-2026",
    studentCode: "FM005-ALUNO-E2E",
    studentName: "Aluno FM-005",
    studentNewPassword: "Senha-Aluno-E2E-2026",
  },
  schools: {
    teacherOne: { email: "fm006.professor1@example.invalid", name: "Professor Multi Escola" },
    teacherTwo: { email: "fm006.professor2@example.invalid", name: "Professor Escola Única" },
    coordinator: { email: "fm006.coordenador@example.invalid", name: "Coordenador FM-006" },
    linkCandidate: { email: "fm006.vinculo@example.invalid", name: "Professor para Vínculo" },
    noMembership: { email: "fm006.sem-escola@example.invalid", name: "Adulto sem Escola" },
    schoolA: { name: "Escola Azul E2E", code: "E2E-FM006-A" },
    schoolB: { name: "Escola Branca E2E", code: "E2E-FM006-B" },
    schoolC: { name: "Escola Celeste E2E", code: "E2E-FM006-C" },
    created: { name: "Escola Criada E2E", code: "E2E-FM006-CREATED" },
  },
  academics: {
    year: 2097,
    className: "Turma FM-007 E2E",
    updatedClassName: "Turma FM-007 Atualizada",
  },
  students: {
    year: 2096,
    name: "Aluno FM-008 E2E",
    classA: "Turma FM-008 Azul",
    classB: "Turma FM-008 Branca",
    temporaryPassword: "Senha-Aluno-FM008-2026",
    newPassword: "Nova-Senha-FM008-2026",
  },
} as const;
