import Link from "next/link";
import { AppShell } from "@/src/components/layout/app-shell";
import { LogoutForm } from "@/src/features/auth/logout-form";
import { SchoolSwitcher } from "@/src/features/schools/school-forms";
import { requireArea } from "@/src/server/auth/guard";
import { listTeacherActivities } from "@/src/server/activities/service";
import { listAvailableSchools } from "@/src/server/schools/service";

const navigation=[{href:"/professor",label:"Visão geral"},{href:"/professor/turmas",label:"Minhas turmas"},{href:"/questoes",label:"Banco de questões"},{href:"/atividades",label:"Atividades"}];
const labels={DRAFT:"Rascunho",OPEN:"Aberta",CLOSED:"Encerrada"} as const;
export default async function ActivitiesPage(){const session=await requireArea("professor");const school=session.schoolContext!;const actor={...session.user};const [activities,schools]=await Promise.all([listTeacherActivities({actor,schoolId:school.schoolId}),listAvailableSchools(session.user.id)]);return <AppShell areaLabel="Professor" currentUserLabel={session.user.name} navigation={navigation} accountAction={<LogoutForm/>} contextAction={<SchoolSwitcher userId={session.user.id} schools={schools} currentSchoolId={school.schoolId}/>} statusLabel={school.schoolName}><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Atividades</h1><p className="mt-2 text-muted">Crie uma seleção fixa, confira a cobertura e acompanhe respostas certas e erradas.</p></div><Link href="/atividades/nova" className="inline-flex min-h-11 items-center rounded-control bg-brand px-4 font-bold text-white">Nova atividade</Link></header>{activities.length===0?<p className="mt-6 rounded-panel border border-border bg-surface p-5 text-muted">Nenhuma atividade criada nesta escola.</p>:<ul className="mt-6 grid gap-4 md:grid-cols-2">{activities.map((activity)=><li key={activity.id} className="rounded-panel border border-border bg-surface p-5"><div className="flex justify-between gap-3"><h2 className="text-lg font-bold">{activity.title}</h2><span className="text-sm font-bold text-brand">{labels[activity.status]}</span></div><p className="mt-2 text-sm text-muted">{activity.classGroup.name} · {activity.classGroup.grade}º ano</p><p className="mt-1 text-sm text-muted">Meta {activity.targetCount} · {activity._count.questionVersions} questões · {activity._count.participations} alunos</p><Link href={`/atividades/${activity.id}`} className="mt-4 inline-flex min-h-11 items-center rounded-control border border-brand px-4 font-bold text-brand">Ver atividade</Link></li>)}</ul>}</AppShell>}
