import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { prisma } from "../../src/lib/prisma";
import { hashPassword } from "../../src/server/auth/password";
import type { AuthenticatedPrincipal } from "../../src/server/auth/policies";
import { assertDatabaseMarker } from "../../src/server/database/marker";
import { readDatabaseEnvironment } from "../../src/server/database/environment";
import { closeActivity, createActivity, getStudentActivity, getTeacherActivity, listStudentActivities, openActivity, recordAcceptedAnswer, updateActivity } from "../../src/server/activities/service";
import { createRichQuestion } from "../../src/server/questions/content-service";
import { createTheme } from "../../src/server/questions/service";

const suffix=randomUUID();const users:string[]=[];let schoolId="";let classId="";let themeId="";let enrollmentId="";let teacher:AuthenticatedPrincipal;let outsider:AuthenticatedPrincipal;let student:AuthenticatedPrincipal;let activityId="";
const content=(difficulty:number)=>({grade:3,difficulty,themeId,statement:`Quanto vale ${difficulty} mais zero?`,answerType:"NUMERIC" as const,numericExpected:String(difficulty),explanation:`O resultado é ${difficulty}.`});

describe.sequential("FM-013 to FM-015 activity lifecycle against PostgreSQL",()=>{
  beforeAll(async()=>{await assertDatabaseMarker(prisma,readDatabaseEnvironment().appEnvId);const passwordHash=await hashPassword("FM013-Teste-2026");const [adminRow,teacherRow,outsiderRow,studentRow]=await Promise.all([
    prisma.user.create({data:{name:"FM013 Admin",email:`admin-${suffix}@example.invalid`,normalizedEmail:`admin-${suffix}@example.invalid`,passwordHash,globalRole:"SEMED_ADMIN"}}),
    prisma.user.create({data:{name:"FM013 Professor",email:`teacher-${suffix}@example.invalid`,normalizedEmail:`teacher-${suffix}@example.invalid`,passwordHash}}),
    prisma.user.create({data:{name:"FM013 Outro",email:`other-${suffix}@example.invalid`,normalizedEmail:`other-${suffix}@example.invalid`,passwordHash}}),
    prisma.user.create({data:{name:"FM014 Aluno",studentCode:`FM014-${suffix}`,passwordHash}}),
  ]);users.push(adminRow.id,teacherRow.id,outsiderRow.id,studentRow.id);const admin={id:adminRow.id,name:adminRow.name,globalRole:"SEMED_ADMIN" as const,studentCode:null};teacher={id:teacherRow.id,name:teacherRow.name,globalRole:null,studentCode:null};outsider={id:outsiderRow.id,name:outsiderRow.name,globalRole:null,studentCode:null};student={id:studentRow.id,name:studentRow.name,globalRole:null,studentCode:studentRow.studentCode};const school=await prisma.school.create({data:{name:"FM013 Escola",externalCode:`FM013-${suffix}`}});schoolId=school.id;const year=await prisma.academicYear.create({data:{schoolId,year:2094}});const group=await prisma.classGroup.create({data:{schoolId,academicYearId:year.id,grade:3,name:"FM013 3A",normalizedName:`fm013-${suffix}`}});classId=group.id;for(const actor of [teacher,outsider]){const membership=await prisma.schoolMembership.create({data:{userId:actor.id,schoolId,role:"TEACHER"}});await prisma.teacherClassAssignment.create({data:{membershipId:membership.id,teacherId:actor.id,schoolId,classId}})}const enrollment=await prisma.enrollment.create({data:{studentId:student.id,schoolId,classId}});enrollmentId=enrollment.id;themeId=(await createTheme({actor:admin,name:`FM013 Tema ${suffix}`})).id;const ids=[];for(let difficulty=1;difficulty<=6;difficulty++){const owner=difficulty<=3?admin:teacher;const question=await createRichQuestion({actor:owner,content:content(difficulty)});const detail=await prisma.questionVersion.findFirstOrThrow({where:{questionId:question.id},select:{id:true}});ids.push(detail.id)}const created=await createActivity({actor:teacher,schoolId,classId,title:"Fluência mista",instructions:"Resolva no seu ritmo.",targetCount:2,questionVersionIds:ids});activityId=created.id;});
  afterAll(async()=>{if(activityId){await prisma.activityAnswerReceipt.deleteMany({where:{participation:{activityId}}});await prisma.activityParticipation.deleteMany({where:{activityId}});await prisma.activityQuestionVersion.deleteMany({where:{activityId}});await prisma.activity.deleteMany({where:{id:activityId}})}await prisma.auditEvent.deleteMany({where:{actorId:{in:users}}});const questions=await prisma.question.findMany({where:{createdById:{in:users}},select:{id:true}});const qids=questions.map(({id})=>id);const versions=await prisma.questionVersion.findMany({where:{questionId:{in:qids}},select:{id:true}});const vids=versions.map(({id})=>id);await prisma.questionOption.deleteMany({where:{versionId:{in:vids}}});await prisma.questionMedia.deleteMany({where:{versionId:{in:vids}}});await prisma.questionVersion.deleteMany({where:{id:{in:vids}}});await prisma.question.deleteMany({where:{id:{in:qids}}});if(themeId)await prisma.theme.delete({where:{id:themeId}});await prisma.enrollment.deleteMany({where:{id:enrollmentId}});await prisma.teacherClassAssignment.deleteMany({where:{teacherId:{in:users}}});await prisma.schoolMembership.deleteMany({where:{userId:{in:users}}});await prisma.classGroup.deleteMany({where:{schoolId}});await prisma.academicYear.deleteMany({where:{schoolId}});await prisma.school.deleteMany({where:{id:schoolId}});await prisma.user.deleteMany({where:{id:{in:users}}});await prisma.$disconnect()});

  it("keeps a draft editable, rejects foreign ownership, and reports complete coverage without answers",async()=>{const detail=await getTeacherActivity({actor:teacher,activityId});expect(detail.coverage).toMatchObject({complete:true,gaps:[]});expect(JSON.stringify(detail)).not.toContain("numericExpected");await expect(getTeacherActivity({actor:{...outsider,id:randomUUID()},activityId})).rejects.toMatchObject({code:"FORBIDDEN"});await expect(updateActivity({actor:teacher,activityId,revision:99,title:"Conflito",targetCount:2,questionVersionIds:detail.versions.map(({id})=>id)})).rejects.toMatchObject({code:"STATE_CONFLICT"});});

  it("opens with historical recipients and separates correct, incorrect, retry, and extra answers",async()=>{const detail=await getTeacherActivity({actor:teacher,activityId});const opened=await openActivity({actor:teacher,activityId,revision:detail.revision});expect(opened.status).toBe("OPEN");await expect(openActivity({actor:teacher,activityId,revision:detail.revision})).rejects.toMatchObject({code:"STATE_CONFLICT"});const firstId=randomUUID();expect(await recordAcceptedAnswer({activityId,studentId:student.id,clientActionId:firstId,outcome:"CORRECT"})).toMatchObject({acceptedNumber:1,isExtra:false,retried:false});expect(await recordAcceptedAnswer({activityId,studentId:student.id,clientActionId:firstId,outcome:"CORRECT"})).toMatchObject({acceptedNumber:1,retried:true});await recordAcceptedAnswer({activityId,studentId:student.id,clientActionId:randomUUID(),outcome:"INCORRECT"});await recordAcceptedAnswer({activityId,studentId:student.id,clientActionId:randomUUID(),outcome:"INCORRECT"});const own=await getStudentActivity({actor:student,activityId});expect(own).toMatchObject({acceptedAnswers:3,correctAnswers:1,incorrectAnswers:2,extraAnswers:1});expect(own.targetReachedAt).toBeTruthy();expect(await listStudentActivities(student)).toHaveLength(1);await expect(getStudentActivity({actor:{...student,id:randomUUID()},activityId})).rejects.toMatchObject({code:"NOT_FOUND"});});

  it("serializes closing against a new answer and preserves a reconciled invariant",async()=>{const detail=await getTeacherActivity({actor:teacher,activityId});const actionId=randomUUID();const [closing,answer]=await Promise.allSettled([closeActivity({actor:teacher,activityId,revision:detail.revision}),recordAcceptedAnswer({activityId,studentId:student.id,clientActionId:actionId,outcome:"CORRECT"})]);expect(closing.status).toBe("fulfilled");const stored=await getStudentActivity({actor:student,activityId});if(answer.status==="fulfilled")expect(stored.acceptedAnswers).toBe(4);else expect(stored.acceptedAnswers).toBe(3);expect(stored.activity.status).toBe("CLOSED");await expect(recordAcceptedAnswer({activityId,studentId:student.id,clientActionId:randomUUID(),outcome:"CORRECT"})).rejects.toMatchObject({code:"STATE_CONFLICT"});await expect(closeActivity({actor:teacher,activityId,revision:detail.revision})).rejects.toMatchObject({code:"STATE_CONFLICT"});});
});
