import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { prisma } from "../../src/lib/prisma";
import { hashPassword } from "../../src/server/auth/password";
import type { AuthenticatedPrincipal } from "../../src/server/auth/policies";
import { assertDatabaseMarker } from "../../src/server/database/marker";
import { readDatabaseEnvironment } from "../../src/server/database/environment";
import { correctPreviewAnswer,createRichQuestion,createRichVersion,getChallengePreview } from "../../src/server/questions/content-service";
import { createTheme,getEligibleQuestion,listEligibleQuestions } from "../../src/server/questions/service";
import { decideSubmission,startSubmissionReview,submitQuestionVersion } from "../../src/server/questions/sharing-service";

const suffix=randomUUID();const userIds:string[]=[];const schoolIds:string[]=[];let admin:AuthenticatedPrincipal;let teacherA:AuthenticatedPrincipal;let teacherB:AuthenticatedPrincipal;let themeId:string;
const png=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0]);

describe.sequential("question editor and SEMED sharing against PostgreSQL",()=>{
  beforeAll(async()=>{await assertDatabaseMarker(prisma,readDatabaseEnvironment().appEnvId);const passwordHash=await hashPassword("FM011-Teste-2026");const users=await Promise.all([prisma.user.create({data:{name:"FM011 Admin",email:`fm011-admin-${suffix}@example.invalid`,normalizedEmail:`fm011-admin-${suffix}@example.invalid`,passwordHash,globalRole:"SEMED_ADMIN"}}),prisma.user.create({data:{name:"FM011 Professor A",email:`fm011-a-${suffix}@example.invalid`,normalizedEmail:`fm011-a-${suffix}@example.invalid`,passwordHash}}),prisma.user.create({data:{name:"FM011 Professor B",email:`fm011-b-${suffix}@example.invalid`,normalizedEmail:`fm011-b-${suffix}@example.invalid`,passwordHash}})]);userIds.push(...users.map(({id})=>id));admin={id:users[0]!.id,name:users[0]!.name,globalRole:"SEMED_ADMIN",studentCode:null};teacherA={id:users[1]!.id,name:users[1]!.name,globalRole:null,studentCode:null};teacherB={id:users[2]!.id,name:users[2]!.name,globalRole:null,studentCode:null};const school=await prisma.school.create({data:{name:"FM011 Escola",externalCode:`FM011-${suffix}`}});schoolIds.push(school.id);const year=await prisma.academicYear.create({data:{schoolId:school.id,year:2093}});const group=await prisma.classGroup.create({data:{schoolId:school.id,academicYearId:year.id,grade:2,name:"FM011 A",normalizedName:`fm011-${suffix}`}});for(const teacher of [teacherA,teacherB]){const membership=await prisma.schoolMembership.create({data:{userId:teacher.id,schoolId:school.id,role:"TEACHER"}});await prisma.teacherClassAssignment.create({data:{membershipId:membership.id,teacherId:teacher.id,schoolId:school.id,classId:group.id}})}themeId=(await createTheme({actor:admin,name:`Números ${suffix}`})).id});
  afterAll(async()=>{await prisma.auditEvent.deleteMany({where:{actorId:{in:userIds}}});await prisma.questionSubmission.deleteMany({where:{submitterId:{in:userIds}}});const versions=await prisma.questionVersion.findMany({where:{createdById:{in:userIds}},select:{id:true}});const versionIds=versions.map(({id})=>id);await prisma.questionMedia.deleteMany({where:{versionId:{in:versionIds}}});await prisma.questionOption.deleteMany({where:{versionId:{in:versionIds}}});const published=await prisma.question.findMany({where:{createdById:{in:userIds},sourceQuestionId:{not:null}},select:{id:true}});const publishedIds=published.map(({id})=>id);await prisma.questionVersion.deleteMany({where:{questionId:{in:publishedIds}}});await prisma.question.deleteMany({where:{id:{in:publishedIds}}});await prisma.questionVersion.deleteMany({where:{id:{in:versionIds}}});await prisma.question.deleteMany({where:{createdById:{in:userIds}}});if(themeId)await prisma.theme.delete({where:{id:themeId}});await prisma.teacherClassAssignment.deleteMany({where:{teacherId:{in:userIds}}});await prisma.schoolMembership.deleteMany({where:{userId:{in:userIds}}});await prisma.classGroup.deleteMany({where:{schoolId:{in:schoolIds}}});await prisma.academicYear.deleteMany({where:{schoolId:{in:schoolIds}}});await prisma.school.deleteMany({where:{id:{in:schoolIds}}});await prisma.user.deleteMany({where:{id:{in:userIds}}});await prisma.$disconnect()});

  it("returns a challenge DTO without the answer and corrects only after submission",async()=>{const created=await createRichQuestion({actor:teacherA,content:{grade:2,difficulty:3,themeId,statement:"Qual alternativa representa quatro?",answerType:"MULTIPLE_CHOICE",explanation:"Dois mais dois formam quatro.",options:[{text:"4",isCorrect:true},{text:"5",isCorrect:false}],media:{bytes:png,mimeType:"image/png",altText:"Quatro pontos azuis"}}});const detail=await getEligibleQuestion({actor:teacherA,questionId:created.id});const version=detail.versions[0]!;const challenge=await getChallengePreview({actor:teacherA,versionId:version.id});expect(JSON.stringify(challenge)).not.toMatch(/isCorrect|numericExpected|correctAnswer|explanation/);expect(challenge.image?.url).toMatch(/\/api\/questoes\/midia\//);const correctId=version.options.find(({isCorrect})=>isCorrect)!.stableId;await expect(correctPreviewAnswer({actor:teacherA,versionId:version.id,answer:correctId})).resolves.toMatchObject({correct:true,correctAnswer:"4"});});

  it("preserves option identities when reordered and accepts comma numeric input",async()=>{const created=await createRichQuestion({actor:teacherA,content:{grade:2,difficulty:2,themeId,statement:"Selecione o resultado de 3 + 3.",answerType:"MULTIPLE_CHOICE",options:[{text:"6",isCorrect:true},{text:"7",isCorrect:false}]}});const first=(await getEligibleQuestion({actor:teacherA,questionId:created.id})).versions[0]!;const reordered=[...first.options].reverse().map(({stableId,text,isCorrect})=>({stableId,text,isCorrect}));await createRichVersion({actor:teacherA,questionId:created.id,revision:created.revision,content:{grade:2,difficulty:2,themeId,statement:"Selecione o resultado de três mais três.",answerType:"MULTIPLE_CHOICE",options:reordered}});const latest=(await getEligibleQuestion({actor:teacherA,questionId:created.id})).versions[0]!;expect(latest.options[0]?.stableId).toBe(first.options[1]?.stableId);expect(latest.options.find(({isCorrect})=>isCorrect)?.stableId).toBe(first.options.find(({isCorrect})=>isCorrect)?.stableId);const numeric=await createRichQuestion({actor:teacherA,content:{grade:2,difficulty:1,themeId,statement:"Quanto é a metade de cinco?",answerType:"NUMERIC",numericExpected:"2,5"}});const numericVersion=(await getEligibleQuestion({actor:teacherA,questionId:numeric.id})).versions[0]!;await expect(correctPreviewAnswer({actor:teacherA,versionId:numericVersion.id,answer:"2.500"})).resolves.toMatchObject({correct:true});});

  it("publishes an idempotent, traceable copy without exposing the private original",async()=>{const source=await createRichQuestion({actor:teacherA,content:{grade:2,difficulty:4,themeId,statement:"Questão particular enviada à rede.",answerType:"MULTIPLE_CHOICE",options:[{text:"Correta",isCorrect:true},{text:"Incorreta",isCorrect:false}],media:{bytes:png,mimeType:"image/png",altText:"Dois blocos"}}});const sourceDetail=await getEligibleQuestion({actor:teacherA,questionId:source.id});const version=sourceDetail.versions[0]!;const submitted=await submitQuestionVersion({actor:teacherA,versionId:version.id});await expect(submitQuestionVersion({actor:teacherA,versionId:version.id})).resolves.toMatchObject({id:submitted.id});await expect(startSubmissionReview({actor:teacherB,submissionId:submitted.id,revision:submitted.revision})).rejects.toMatchObject({code:"FORBIDDEN"});const reviewing=await startSubmissionReview({actor:admin,submissionId:submitted.id,revision:submitted.revision});const approved=await decideSubmission({actor:admin,submissionId:submitted.id,revision:reviewing.revision,decision:"APPROVED_PUBLISHED",note:"Conteúdo aprovado."});expect(approved.publishedQuestionId).not.toBe(source.id);await expect(decideSubmission({actor:admin,submissionId:submitted.id,revision:reviewing.revision,decision:"APPROVED_PUBLISHED",note:"Retry"})).resolves.toMatchObject({publishedQuestionId:approved.publishedQuestionId});const published=await getEligibleQuestion({actor:admin,questionId:approved.publishedQuestionId!});expect(published).toMatchObject({origin:"SEMED",sourceQuestionId:source.id,sourceVersionId:version.id});expect(published.versions[0]).toMatchObject({contentHash:version.contentHash,statement:version.statement});const visibleToOther=await listEligibleQuestions({actor:teacherB});expect(visibleToOther.some(({id})=>id===approved.publishedQuestionId)).toBe(true);expect(visibleToOther.some(({id})=>id===source.id)).toBe(false);});

  it("records requests for changes and rejection without creating a network copy",async()=>{for(const decision of ["CHANGES_REQUESTED","REJECTED"] as const){const source=await createRichQuestion({actor:teacherA,content:{grade:2,difficulty:5,themeId,statement:`Questão destinada à decisão ${decision}.`,answerType:"NUMERIC",numericExpected:"12"}});const version=(await getEligibleQuestion({actor:teacherA,questionId:source.id})).versions[0]!;const submitted=await submitQuestionVersion({actor:teacherA,versionId:version.id});const decided=await decideSubmission({actor:admin,submissionId:submitted.id,revision:submitted.revision,decision,note:"Justificativa pedagógica registrada."});expect(decided).toMatchObject({status:decision,publishedQuestionId:null,publishedVersionId:null});await expect(decideSubmission({actor:admin,submissionId:submitted.id,revision:submitted.revision,decision:"APPROVED_PUBLISHED"})).rejects.toMatchObject({code:"STATE_CONFLICT"});}});
});
