import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/src/components/layout/app-shell";
import { LogoutForm } from "@/src/features/auth/logout-form";
import { GamePanel, StartGameButton } from "@/src/features/games/game-panel";
import { AuthorizationError } from "@/src/server/auth/errors";
import { requireArea } from "@/src/server/auth/guard";
import { getStudentActivity } from "@/src/server/activities/service";
import { getActiveGameForActivity } from "@/src/server/games/service";
const navigation=[{href:"/aluno",label:"Início"}];
export default async function StudentActivityPage({params}:{params:Promise<{id:string}>}){const session=await requireArea("aluno");const {id}=await params;const actor={...session.user};let item;try{item=await getStudentActivity({actor,activityId:id});}catch(error){if(error instanceof AuthorizationError&&(error.code==="NOT_FOUND"||error.code==="FORBIDDEN"))notFound();throw error;}const game=item.activity.status==="OPEN"?await getActiveGameForActivity({actor,activityId:id}):null;const target=Math.min(item.acceptedAnswers,item.activity.targetCount);const met=Boolean(item.targetReachedAt);return <AppShell areaLabel="Aluno" currentUserLabel={session.user.name} navigation={navigation} accountAction={<LogoutForm/>} statusLabel={item.activity.status==="OPEN"?"Atividade aberta":"Atividade encerrada"}><div className="grid gap-6"><header><Link href="/aluno" className="font-bold text-brand">← Voltar ao início</Link><h1 className="mt-3 text-3xl font-bold">{item.activity.title}</h1><p className="mt-2 text-muted">{item.activity.classGroup.name} · meta de {item.activity.targetCount} respostas aceitas</p></header><section className="rounded-panel border border-border bg-surface p-5"><h2 className="text-xl font-bold">Seu progresso</h2><p className="mt-3 text-3xl font-bold text-brand">{target}/{item.activity.targetCount}</p><progress className="mt-3 h-3 w-full" max={item.activity.targetCount} value={target}/><p className="mt-3 font-semibold">{met?"Meta cumprida — você pode continuar praticando.":item.acceptedAnswers?"Em andamento":"Ainda não iniciada"}</p><dl className="mt-4 grid grid-cols-3 gap-3 text-center"><div className="rounded-control bg-blue-50 p-3"><dt className="text-sm text-muted">Certas</dt><dd className="text-xl font-bold">{item.correctAnswers}</dd></div><div className="rounded-control bg-blue-50 p-3"><dt className="text-sm text-muted">Erradas</dt><dd className="text-xl font-bold">{item.incorrectAnswers}</dd></div><div className="rounded-control bg-blue-50 p-3"><dt className="text-sm text-muted">Extras</dt><dd className="text-xl font-bold">{item.extraAnswers}</dd></div></dl></section>{item.activity.status==="CLOSED"?<p role="status" className="rounded-panel border border-border bg-blue-50 p-5 font-semibold">Esta atividade foi encerrada pelo professor. Seu progresso continua salvo.</p>:game?<GamePanel key={game.revision} activityId={id} game={game}/>:<section className="rounded-panel border border-border bg-surface p-5"><h2 className="text-xl font-bold">Praticar com Ludo</h2><p className="mt-2 mb-4 text-muted">A partida é salva no servidor e retomada nesta atividade.</p><StartGameButton activityId={id}/></section>}</div></AppShell>}
