import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/src/components/layout/app-shell";
import { LogoutForm } from "@/src/features/auth/logout-form";
import { ReviewSubmissionForm } from "@/src/features/questions/rich-editor";
import { getCurrentSession } from "@/src/server/auth/session";
import { listReviewQueue } from "@/src/server/questions/sharing-service";

export default async function ReviewQueuePage(){const session=await getCurrentSession();if(!session)redirect("/login");const actor={id:session.user.id,name:session.user.name,globalRole:session.user.globalRole,studentCode:session.user.studentCode};if(actor.globalRole!=="SEMED_ADMIN")redirect(session.destination);const queue=await listReviewQueue(actor);const navigation=[{href:"/admin",label:"Visão geral"},{href:"/questoes",label:"Banco de questões"},{href:"/questoes/revisao",label:"Revisão SEMED"}];return <AppShell areaLabel="Administração" currentUserLabel={session.user.name} navigation={navigation} accountAction={<LogoutForm/>} statusLabel="Fila SEMED"><div className="grid gap-6"><header><Link href="/questoes" className="font-semibold text-brand">← Voltar ao banco</Link><h1 className="mt-3 text-3xl font-bold">Revisão de questões enviadas</h1></header>{queue.length===0?<p className="rounded-panel border border-border bg-surface p-5 text-muted">Nenhuma questão enviada.</p>:<ul className="grid gap-4">{queue.map((item)=><li key={item.id} className="rounded-panel border border-border bg-surface p-5"><div className="flex flex-wrap gap-2 text-xs font-bold uppercase text-brand"><span>{item.status}</span><span>{item.sourceVersion.grade}º ano</span><span>Dificuldade {item.sourceVersion.difficulty}</span></div><h2 className="mt-3 text-lg font-bold">{item.sourceVersion.theme.name}{item.sourceVersion.skill?` · ${item.sourceVersion.skill.name}`:""}</h2><p className="mt-1 text-sm text-muted">Autor: {item.submitter.name} · versão {item.sourceVersion.versionNumber}</p><p className="my-4">{item.sourceVersion.statement}</p><Link href={`/questoes/${item.sourceVersion.questionId}`} className="mb-4 inline-flex min-h-11 items-center font-semibold text-brand">Abrir questão e prévia</Link><ReviewSubmissionForm submission={{id:item.id,revision:item.revision,status:item.status}}/>{item.decisionNote&&<p className="mt-3 rounded-control bg-background p-3">Observação: {item.decisionNote}</p>}</li>)}</ul>}</div></AppShell>}
