"use client";

import Link from "next/link";
import Image from "next/image";
import { useActionState, useState } from "react";
import { Button } from "@/src/components/ui/button";
import { correctPreviewAnswerAction, createRichQuestionAction, createRichVersionAction, decideSubmissionAction, startReviewAction, submitQuestionAction, type QuestionActionState } from "./actions";

const initial: QuestionActionState = { status: "idle" };
type Taxonomy = { id: string; name: string; skills: { id: string; name: string }[] }[];
type EditorOption = { key: string; stableId: string | null; text: string; isCorrect: boolean };
type EditorInitial = { grade: number; difficulty: number; themeId: string; skillId: string | null; statement: string; answerType: "MULTIPLE_CHOICE" | "NUMERIC" | null; explanation: string | null; numericExpected: string | null; options: { stableId: string; text: string; isCorrect: boolean }[]; media: { id: string; altText: string }[] };

function Result({ state }: { state: QuestionActionState }) {
  if (!state.message) return null;
  return <div role={state.status === "success" ? "status" : "alert"} className={`rounded-control border p-3 text-sm font-medium ${state.status === "success" ? "border-green-200 bg-green-50 text-green-950" : "border-red-200 bg-red-50 text-red-950"}`}>{state.message}{state.createdId && <div className="mt-2"><Link className="font-bold underline" href={`/questoes/${state.createdId}`}>Abrir questão criada</Link></div>}</div>;
}

function defaultOptions(initialValue?: EditorInitial): EditorOption[] {
  if (initialValue?.options.length) return initialValue.options.map((option) => ({ key: option.stableId, stableId: option.stableId, text: option.text, isCorrect: option.isCorrect }));
  return [{ key: "new-1", stableId: null, text: "", isCorrect: true }, { key: "new-2", stableId: null, text: "", isCorrect: false }];
}

export function RichQuestionEditor({ taxonomy, question, initialValue }: { taxonomy: Taxonomy; question?: { id: string; revision: number }; initialValue?: EditorInitial }) {
  const [state, action, pending] = useActionState(question ? createRichVersionAction : createRichQuestionAction, initial);
  const [answerType, setAnswerType] = useState<"MULTIPLE_CHOICE" | "NUMERIC">(initialValue?.answerType ?? "MULTIPLE_CHOICE");
  const [themeId, setThemeId] = useState(initialValue?.themeId ?? taxonomy[0]?.id ?? "");
  const [options, setOptions] = useState<EditorOption[]>(() => defaultOptions(initialValue));
  const [counter, setCounter] = useState(3);
  const skills = taxonomy.find((theme) => theme.id === themeId)?.skills ?? [];
  const update = (key: string, patch: Partial<EditorOption>) => setOptions((current) => current.map((option) => option.key === key ? { ...option, ...patch } : option));
  const move = (index: number, delta: number) => setOptions((current) => { const target = index + delta; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target]!, next[index]!]; return next; });
  const add = () => { if (options.length >= 6) return; const key = `new-${counter}`; setCounter((value) => value + 1); setOptions((current) => [...current, { key, stableId: null, text: "", isCorrect: false }]); };
  const remove = (key: string) => { if (options.length <= 2) return; setOptions((current) => { const removed = current.find((option) => option.key === key); const next = current.filter((option) => option.key !== key); if (removed?.isCorrect && next[0]) next[0] = { ...next[0], isCorrect: true }; return next; }); };
  return <form action={action} className="grid gap-5" aria-busy={pending || undefined} encType="multipart/form-data">
    {question && <><input type="hidden" name="questionId" value={question.id}/><input type="hidden" name="revision" value={question.revision}/></>}
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 font-semibold">Série<select name="grade" defaultValue={initialValue?.grade ?? 1} className="min-h-11 rounded-control border border-border bg-surface px-3">{[1,2,3,4,5].map((value)=><option key={value} value={value}>{value}º ano</option>)}</select></label><label className="grid gap-2 font-semibold">Dificuldade<select name="difficulty" defaultValue={initialValue?.difficulty ?? 1} className="min-h-11 rounded-control border border-border bg-surface px-3">{[1,2,3,4,5,6].map((value)=><option key={value}>{value}</option>)}</select></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 font-semibold">Tema<select name="themeId" value={themeId} onChange={(event)=>setThemeId(event.target.value)} className="min-h-11 rounded-control border border-border bg-surface px-3" required>{taxonomy.map((theme)=><option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label><label className="grid gap-2 font-semibold">Habilidade (opcional)<select key={themeId} name="skillId" defaultValue={initialValue?.themeId === themeId ? initialValue.skillId ?? "" : ""} className="min-h-11 rounded-control border border-border bg-surface px-3"><option value="">Sem habilidade específica</option>{skills.map((skill)=><option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label></div>
    <label className="grid gap-2 font-semibold">Enunciado<textarea name="statement" defaultValue={initialValue?.statement} minLength={5} maxLength={2000} rows={5} className="rounded-control border border-border bg-surface p-3" required/></label>
    <label className="grid gap-2 font-semibold">Tipo de resposta<select name="answerType" value={answerType} onChange={(event)=>setAnswerType(event.target.value as typeof answerType)} className="min-h-11 rounded-control border border-border bg-surface px-3"><option value="MULTIPLE_CHOICE">Alternativas</option><option value="NUMERIC">Numérica exata</option></select></label>
    {answerType === "MULTIPLE_CHOICE" ? <fieldset className="grid gap-3"><legend className="font-bold">Alternativas — marque exatamente uma correta</legend>{options.map((option,index)=><div key={option.key} className="grid gap-2 rounded-control border border-border p-3 sm:grid-cols-[auto_1fr_auto]"><input type="hidden" name="optionKey" value={option.stableId ?? option.key}/><label className="flex min-h-11 items-center gap-2 font-semibold"><input type="radio" name="correctOption" value={option.stableId ?? option.key} checked={option.isCorrect} onChange={()=>setOptions((current)=>current.map((item)=>({...item,isCorrect:item.key===option.key})))} required/>Correta</label><label className="grid gap-1"><span className="sr-only">Texto da alternativa {index+1}</span><input name="optionText" value={option.text} onChange={(event)=>update(option.key,{text:event.target.value})} maxLength={500} className="min-h-11 rounded-control border border-border px-3" aria-label={`Texto da alternativa ${index+1}`} required/></label><div className="flex gap-1"><button type="button" onClick={()=>move(index,-1)} disabled={index===0} className="min-h-11 rounded-control border px-3" aria-label={`Mover alternativa ${index+1} para cima`}>↑</button><button type="button" onClick={()=>move(index,1)} disabled={index===options.length-1} className="min-h-11 rounded-control border px-3" aria-label={`Mover alternativa ${index+1} para baixo`}>↓</button><button type="button" onClick={()=>remove(option.key)} disabled={options.length<=2} className="min-h-11 rounded-control border px-3" aria-label={`Remover alternativa ${index+1}`}>×</button></div></div>)}<button type="button" onClick={add} disabled={options.length>=6} className="min-h-11 rounded-control border border-brand px-4 font-semibold text-brand">Adicionar alternativa</button></fieldset> : <label className="grid gap-2 font-semibold">Resposta numérica esperada<input name="numericExpected" defaultValue={initialValue?.numericExpected ?? ""} inputMode="decimal" placeholder="Ex.: 2,5" className="min-h-11 rounded-control border border-border px-3" required/><span className="text-sm font-normal text-muted">Aceita vírgula ou ponto; sem expressão, unidade ou tolerância implícita.</span></label>}
    <label className="grid gap-2 font-semibold">Explicação após erro (opcional)<textarea name="explanation" defaultValue={initialValue?.explanation ?? ""} maxLength={2000} rows={3} className="rounded-control border border-border p-3"/></label>
    <fieldset className="grid min-w-0 gap-3 rounded-control border border-border p-4"><legend className="font-bold">Imagem opcional</legend>{initialValue?.media[0] && <Image src={`/api/questoes/midia/${initialValue.media[0].id}`} alt={initialValue.media[0].altText} width={640} height={360} unoptimized className="h-auto max-h-64 w-auto max-w-full rounded-control object-contain"/>}<label className="grid min-w-0 gap-2 font-semibold">Arquivo<input type="file" name="image" accept="image/png,image/jpeg,image/webp,image/gif" className="min-h-11 min-w-0 w-full max-w-full rounded-control border border-border p-2"/></label><label className="grid gap-2 font-semibold">Descrição acessível<input name="altText" defaultValue={initialValue?.media[0]?.altText ?? ""} maxLength={300} className="min-h-11 rounded-control border border-border px-3"/></label>{initialValue?.media[0] && <label className="flex items-center gap-2"><input type="checkbox" name="removeMedia" value="yes"/>Remover a imagem nesta nova versão</label>}<p className="text-sm text-muted">PNG, JPEG, WebP ou GIF, até 512 KB. SVG e URL externa são recusados.</p></fieldset>
    <Result state={state}/><Button type="submit" busy={pending}>{question ? "Criar nova versão completa" : "Cadastrar questão completa"}</Button>
  </form>;
}

export function SpeechButton({ text, enabled, label, versionId, optionId }: { text: string; enabled: boolean; label: string; versionId: string; optionId?: string }) {
  const [message,setMessage]=useState<string>();
  const speak=()=>{ if(!enabled || !("speechSynthesis" in window)){setMessage("Áudio indisponível; a resposta foi preservada.");return;} try{window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text));setMessage("Leitura iniciada pela voz do dispositivo.");}catch{setMessage("Falha ao iniciar o áudio; a resposta foi preservada.");}};
  return <div><button type="button" onClick={speak} data-audio-version-id={versionId} data-audio-option-id={optionId} className="min-h-11 rounded-control border border-brand px-4 font-semibold text-brand">{label}</button>{message&&<p role="status" className="mt-2 text-sm text-muted">{message}</p>}</div>;
}

export function ChallengePreview({ challenge, audioEnabled }: { challenge: { id:string;statement:string;answerType:"MULTIPLE_CHOICE"|"NUMERIC";options:{id:string;text:string;position:number}[];image:{url:string;altText:string}|null }; audioEnabled:boolean }) {
  const [state,action,pending]=useActionState(correctPreviewAnswerAction,initial);
  return <div className="grid gap-4"><div className="rounded-panel border border-border bg-background p-5">{challenge.image&&<Image src={challenge.image.url} alt={challenge.image.altText} width={640} height={360} unoptimized className="mb-4 h-auto max-h-72 w-auto max-w-full object-contain"/>}<p className="text-lg font-semibold">{challenge.statement}</p><SpeechButton text={challenge.statement} enabled={audioEnabled} label="Ouvir enunciado" versionId={challenge.id}/><form action={action} className="mt-5 grid gap-3" aria-busy={pending||undefined}><input type="hidden" name="versionId" value={challenge.id}/>{challenge.answerType==="MULTIPLE_CHOICE"?<fieldset className="grid gap-2"><legend className="sr-only">Escolha uma alternativa</legend>{challenge.options.map((option,index)=><div key={option.id} className="grid min-w-0 gap-2 rounded-control border border-border p-3"><label className="flex min-h-11 items-center gap-3"><input type="radio" name="answer" value={option.id} required/><span>{option.text}</span></label><SpeechButton text={option.text} enabled={audioEnabled} label={`Ouvir alternativa ${index+1}`} versionId={challenge.id} optionId={option.id}/></div>)}</fieldset>:<label className="grid gap-2 font-semibold">Sua resposta<input name="answer" inputMode="decimal" className="min-h-11 rounded-control border border-border px-3" required/></label>}<Button type="submit" busy={pending}>Corrigir prévia</Button></form>{state.message&&<div role={state.status==="success"?"status":"alert"} className="mt-4 rounded-control border border-border p-3"><p className="font-bold">{state.message}</p>{state.correction&&!state.correction.correct&&<p>Resposta correta: {state.correction.correctAnswer}</p>}{state.correction?.explanation&&<p className="mt-2">{state.correction.explanation}</p>}</div>}</div></div>;
}

export function SubmitQuestionForm({ questionId, versionId, existingStatus }: { questionId:string;versionId:string;existingStatus?:string }) { const [state,action,pending]=useActionState(submitQuestionAction,initial); return <form action={action} className="grid gap-3" aria-busy={pending||undefined}><input type="hidden" name="questionId" value={questionId}/><input type="hidden" name="versionId" value={versionId}/>{existingStatus?<p className="text-sm font-semibold">Situação do envio: {existingStatus}</p>:<Button type="submit" busy={pending}>Enviar esta versão à SEMED</Button>}<Result state={state}/></form>; }

export function ReviewSubmissionForm({ submission }: { submission:{id:string;revision:number;status:string} }) { const [startState,startAction,startPending]=useActionState(startReviewAction,initial); const [decisionState,decisionAction,decisionPending]=useActionState(decideSubmissionAction,initial); if(["CHANGES_REQUESTED","REJECTED","APPROVED_PUBLISHED"].includes(submission.status)) return <p className="font-semibold">Decisão final: {submission.status}</p>; return <div className="grid gap-4"><form action={startAction} className="grid gap-2"><input type="hidden" name="submissionId" value={submission.id}/><input type="hidden" name="revision" value={submission.revision}/><Button type="submit" busy={startPending}>Iniciar análise</Button><Result state={startState}/></form><form action={decisionAction} className="grid gap-3"><input type="hidden" name="submissionId" value={submission.id}/><input type="hidden" name="revision" value={submission.revision}/><label className="grid gap-2 font-semibold">Decisão<select name="decision" className="min-h-11 rounded-control border border-border px-3"><option value="APPROVED_PUBLISHED">Aprovar e publicar</option><option value="CHANGES_REQUESTED">Solicitar ajustes</option><option value="REJECTED">Recusar</option></select></label><label className="grid gap-2 font-semibold">Observação<textarea name="note" maxLength={1000} rows={3} className="rounded-control border border-border p-3"/></label><Button type="submit" busy={decisionPending}>Registrar decisão</Button><Result state={decisionState}/></form></div>; }
